name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Codespace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh auth status

          gh codespace ssh \
            --codespace orange-trout-g4pqrwrxq4wxfwv75 \
            -- \
            'cd /workspaces/codespaces-blank/my-app &&
            git pull origin main &&
            docker compose up -d --build'    